#pragma once
/**
 * @file StatArbMM.hpp
 * @brief Avellaneda-Stoikov market making strategy.
 * 
 * Computes reservation price and optimal quotes based on:
 *   - Inventory position
 *   - Spread signal (z-score)
 *   - Order flow imbalance
 * 
 * Reference: Avellaneda & Stoikov (2008)
 */

#include <cmath>
#include <algorithm>

#include "../core/Order.hpp"
#include "../signals/SpreadModel.hpp"
#include "../signals/OFI.hpp"

namespace strategy {

/**
 * @brief Quote generated by the market maker.
 */
struct Quote {
    Price bidPrice = PRICE_INVALID;
    Price askPrice = PRICE_INVALID;
    Quantity bidSize = 0;
    Quantity askSize = 0;
    bool valid = false;
};

/**
 * @brief Avellaneda-Stoikov stat-arb market maker.
 * 
 * Features:
 *   - Inventory-adjusted reservation price
 *   - Signal gating (z-score + OFI)
 *   - Configurable risk parameters
 * 
 * Usage:
 * @code
 *   StatArbMM mm;
 *   mm.setInventory(100);  // Long 100 shares
 *   Quote q = mm.computeQuotes(fairPrice, volatility);
 * @endcode
 */
class StatArbMM {
public:
    // ========================================================================
    // Configuration
    // ========================================================================
    
    /** Risk aversion parameter (higher = more aggressive inventory reduction) */
    double gamma = 0.01;
    
    /** Time horizon (fraction of day remaining) */
    double T = 1.0;
    
    /** Base spread (ticks) */
    double baseSpread = 2.0;
    
    /** Default quote size */
    Quantity defaultSize = 100;
    
    /** Z-score entry threshold */
    double zEntryThreshold = 1.5;
    
    /** Z-score exit threshold */
    double zExitThreshold = 0.5;
    
    /** OFI threshold for signal confirmation */
    double ofiThreshold = 0.3;
    
    /** Maximum inventory (absolute) */
    int32_t maxInventory = 1000;

    // ========================================================================
    // State
    // ========================================================================

    /**
     * @brief Set current inventory position.
     * @param inv Signed inventory (positive = long, negative = short)
     */
    void setInventory(int32_t inv) noexcept { inventory_ = inv; }
    
    /**
     * @brief Get current inventory.
     */
    [[nodiscard]] int32_t inventory() const noexcept { return inventory_; }

    // ========================================================================
    // Core Logic
    // ========================================================================

    /**
     * @brief Compute reservation price.
     * 
     * r = s - q * γ * σ² * (T - t)
     * 
     * Where:
     *   s = fair price
     *   q = inventory
     *   γ = risk aversion
     *   σ = volatility
     *   T-t = time remaining
     * 
     * @param fairPrice Current fair price estimate
     * @param volatility Current volatility estimate
     * @return Reservation price
     */
    [[nodiscard]] double reservationPrice(double fairPrice, double volatility) const noexcept {
        return fairPrice - inventory_ * gamma * volatility * volatility * T;
    }

    /**
     * @brief Compute optimal spread.
     * 
     * δ = γ * σ² * (T - t) + (2/γ) * log(1 + γ/k)
     * 
     * Simplified: δ ≈ baseSpread + |inventory| * gamma
     */
    [[nodiscard]] double optimalSpread(double volatility) const noexcept {
        return baseSpread + std::abs(inventory_) * gamma * volatility;
    }

    /**
     * @brief Compute market making quotes.
     * 
     * @param fairPrice Fair price estimate (from spread model)
     * @param volatility Current volatility
     * @param zScore Spread z-score
     * @param ofiValue OFI normalized value
     * @return Quote with bid/ask prices and sizes
     */
    [[nodiscard]] Quote computeQuotes(double fairPrice, double volatility,
                                       double zScore = 0, double ofiValue = 0) const {
        Quote quote;
        
        // Check inventory limits
        if (std::abs(inventory_) >= maxInventory) {
            // Only quote to reduce inventory
            if (inventory_ > 0) {
                quote.askPrice = static_cast<Price>(fairPrice);
                quote.askSize = defaultSize;
                quote.valid = true;
            } else {
                quote.bidPrice = static_cast<Price>(fairPrice);
                quote.bidSize = defaultSize;
                quote.valid = true;
            }
            return quote;
        }

        // Compute reservation price
        double r = reservationPrice(fairPrice, volatility);
        double spread = optimalSpread(volatility);
        
        // Base quotes
        double bidPrice = r - spread / 2.0;
        double askPrice = r + spread / 2.0;
        
        // Signal gating
        bool enterLong = (zScore < -zEntryThreshold) && (ofiValue > -ofiThreshold);
        bool enterShort = (zScore > zEntryThreshold) && (ofiValue < ofiThreshold);
        bool exitLong = (zScore > -zExitThreshold) && (inventory_ > 0);
        bool exitShort = (zScore < zExitThreshold) && (inventory_ < 0);
        
        // Adjust quotes based on signals
        if (enterLong || exitShort) {
            // Aggressive bid
            bidPrice += 1;
            quote.bidSize = defaultSize * 2;
        } else {
            quote.bidSize = defaultSize;
        }
        
        if (enterShort || exitLong) {
            // Aggressive ask
            askPrice -= 1;
            quote.askSize = defaultSize * 2;
        } else {
            quote.askSize = defaultSize;
        }
        
        quote.bidPrice = static_cast<Price>(std::max(0.0, bidPrice));
        quote.askPrice = static_cast<Price>(askPrice);
        quote.valid = true;
        
        return quote;
    }

    /**
     * @brief Update inventory after a fill.
     * @param side Side of the fill
     * @param quantity Filled quantity
     */
    void onFill(OrderSide side, Quantity quantity) noexcept {
        if (side == OrderSide::Buy) {
            inventory_ += quantity;
        } else {
            inventory_ -= quantity;
        }
    }

    /**
     * @brief Reset strategy state.
     */
    void reset() noexcept {
        inventory_ = 0;
    }

private:
    int32_t inventory_ = 0;
};

} // namespace strategy
